name: 'Print stuff'
description: 'Greet someone'
inputs:
  env:
    description: The environment
    required: true
runs:
  using: "composite"
  steps:
    - run: echo The current environment is ${{ inputs.env }}.
      shell: bash