name: dummy

on: push

env:
  one: 1
  two: zwei
  three: tres

jobs:
  call-workflow-passing-data:
    uses: elben10/action-composition/.github/workflows/stage_deploy.yml@master
    with:
      env_name: ${{ env.one }}