name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: elben10/action-composition/.github/workflows/workflow-B.yml@main
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}