name: Call a reusable workflow

on:
  push:
    branches:
      - production

jobs:
  env:
    NAME: PRODUCTION
  call-workflow-passing-data:
    uses: elben10/action-composition/.github/workflows/stage_deploy.yml@master
    with:
      env_name: ${{ env.NAME }}