name: Call a reusable workflow

on:
  push:
    branches:
      - master

env:
  SERVER: production

jobs:
  call-workflow-passing-data:
    uses: elben10/action-composition/.github/workflows/stage_deploy.yml@master
    with:
      env_name: NAME