name: Reusable workflow example

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.env_name }}